name: gym-dev

services:
  gym-crm-databade:
    container_name: gym-crm-database
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    environment:
      - POSTGRES_DB=gym_crm_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - gym_dev_crm_database_volumes:/var/lib/postgresql
    networks:
      - gym-dev-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d gym_crm_database" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s

networks:
  gym-dev-network:
    external: true

volumes:
  gym_dev_crm_database_volumes:
