name: gym-dev

services:
  gym-crm-database:
    container_name: gym-crm-database
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    environment:
      - POSTGRES_DB=gym_crm_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - gym_dev_crm_database_volumes:/var/lib/postgresql
    networks:
      - gym-dev-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d gym_crm_database" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  gym-crm-server:
    container_name: gym-crm-server
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "8084:8084"
    networks:
      - gym-dev-network
    depends_on:
      gym-crm-database:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

networks:
  gym-dev-network:
    external: true

volumes:
  gym_dev_crm_database_volumes:
