name: gym-local

services:
  gym-db:
    container_name: gym-local-postgres
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    environment:
      - POSTGRES_DB=gym_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - gym_db_local_volume:/var/lib/postgresql
    networks:
      - gym-shared-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d gym_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  gym-shared-network:
    external: true

volumes:
  gym_db_local_volume:
    driver: local
