spring:
  datasource:
    url: jdbc:postgresql://gym-db:5432/gym_db?currentSchema=gym_schema
    username: gym_user
    password: vG8k2Pz9mN4Xw7Tq


  liquibase:
    contexts: default

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: WARN
    com.epam.gym: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
