# Application
spring:
  output:
    ansi:
      enabled: always
  application:
    name: gym

  # Json
  jackson:
    property-naming-strategy: SNAKE_CASE

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_schema: gym_schema
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20


  # Liquibase
  liquibase:
    default-schema: gym_schema
    change-log: classpath:db/changelog/main-changelog.yaml
    enabled: true
    contexts: default

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health"
      base-path: /actuator
  endpoint:
    health:
      show-details: never
      show-components: never
    prometheus:
      enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: false
  info:
    env:
      enabled: false

# Logging
logging:
  level:
    root: WARN
    com.epam.gym: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
  pattern:
    correlation: "[${spring.application.name:},%X{requestUid:-}] "
    console: "%clr([){faint}%clr(${spring.application.name:}){cyan}%clr( : ){faint}%clr(%X{requestUid:-}){magenta}%clr(]){faint} %clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%-5level) %clr([%thread]){faint} %clr(%logger{36}){cyan} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# Swagger
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Security
application:
  request-uid:
    header-name: "X-Request-Uid"
    mdc-key: "requestUid"
  auth:
    max-login-attempts: 3
    block-duration: PT15M
    jwt-expiration: 86400
  user:
    username-delimiter: "."
  cors:
    allowed-origins:
      - "http://localhost:8080"
      - "http://localhost:3000"
      - "http://localhost:9090"
      - "http://localhost:8081"
  swagger:
    server-url: "http://localhost:8080"
    server-description: "Local server"

eureka:
  client:
    enabled: false
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
