databaseChangeLog:
  - changeSet:
      id: 2026-02-04-03
      author: Klim Birukou <klim_birukou@epam.com>
      changes:
        - createTable:
            tableName: trainer
            schemaName: gym_schema
            remarks: Create table for storing trainers
            columns:
              - column:
                  name: uid
                  type: uuid
                  constraints:
                    primaryKey: true
                    primaryKeyName: pk_trainer
              - column:
                  name: specialization
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: user_uid
                  type: uuid
                  constraints:
                    nullable: false
                    unique: true
                    foreignKeyName: fk_trainer_to_user
                    references: gym_schema.user(uid)
