databaseChangeLog:
  - changeSet:
      id: 2026-02-10-01
      author: Klim Birukou <klim_birukou@epam.com>
      changes:
        - createTable:
            tableName: training_type
            schemaName: gym_crm_schema
            remarks: Stores training-type enumeration to training
            columns:
              - column:
                  name: uid
                  type: uuid
                  defaultValueComputed: gen_random_uuid()
                  constraints:
                    primaryKey: true
                    primaryKeyName: pk_training_type
                    nullable: false
              - column:
                  name: name
                  type: varchar(255)
                  constraints:
                    nullable: false
                    unique: true
                    uniqueConstraintName: uk_training_type_name
