databaseChangeLog:
  - changeSet:
      id: 2026-02-06-01
      author: Klim Birukou <klim_birukou@epam.com>
      changes:
        - createTable:
            tableName: training
            schemaName: gym_crm_schema
            remarks: Create table for storing trainings
            columns:
              - column:
                  name: uid
                  type: uuid
                  constraints:
                    primaryKey: true
                    primaryKeyName: pk_training
              - column:
                  name: name
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: date
                  type: date
                  constraints:
                    nullable: false
              - column:
                  name: duration
                  type: bigint
                  constraints:
                    nullable: false
              - column:
                  name: training_type_uid
                  type: uuid
                  constraints:
                    nullable: false
              - column:
                  name: trainee_uid
                  type: uuid
                  constraints:
                    nullable: false
              - column:
                  name: trainer_uid
                  type: uuid
                  constraints:
                    nullable: false
        - addForeignKeyConstraint:
            baseTableName: training
            baseColumnNames: training_type_uid
            referencedTableName: training_type
            referencedColumnNames: uid
            constraintName: fk_training_to_training_type
        - addForeignKeyConstraint:
            baseTableName: training
            baseColumnNames: trainee_uid
            referencedTableName: trainee
            referencedColumnNames: uid
            constraintName: fk_training_to_trainee
            onDelete: CASCADE
            onUpdate: CASCADE
        - addForeignKeyConstraint:
            baseTableName: training
            baseColumnNames: trainer_uid
            referencedTableName: trainer
            referencedColumnNames: uid
            constraintName: fk_training_to_trainer
            onDelete: CASCADE
            onUpdate: CASCADE
