DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_user WHERE usename = 'gym_user') THEN
        CREATE USER gym_user WITH ENCRYPTED PASSWORD 'vG8k2Pz9mN4Xw7Tq';
    END IF;
END
$$;


CREATE SCHEMA IF NOT EXISTS gym_schema AUTHORIZATION gym_user;

GRANT ALL PRIVILEGES ON SCHEMA gym_schema TO gym_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA gym_schema GRANT ALL ON TABLES TO gym_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA gym_schema GRANT ALL ON SEQUENCES TO gym_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA gym_schema GRANT ALL ON TABLES TO gym_user;
